### PR TITLE
Enforce `.atf` extension when submitting tasks to the server

### LINKED ISSUE #99: If filename doesn't have `.atf` extension, validation/lemmatisation of an invalid file never returns errors
**Describe the problem**

Similarly to #90 (which is now fixed on the server side), if an ATF file doesn't have atf extension, running validation or lemmatisation on it never returns errors.

I'm not sure how to best address this issue.  I see two options:

* show a warning that the file doesn't have `.atf` extension when trying to do validation/lemmatisation, not having the extension is likely an oversight
* we can artificially add the extension if it's missing, similarly to what we initially did in #91.

I guess the decision boils down to whether we want to force the extension in the filename or not

**To Reproduce**

Create an ATF with this content:
```
&X001001 = JCS 48, 089
#project: cams/gkab
#atf: lang akk-x-stdbab
#atf: use unicode
#atf: use math
@tablet
@obverse

1.	[MU] 1.03-KAM {iti}AB GE₆ U₄ 2-KAM
#lem: šatti[year]N; n; Ṭebetu[1]MN; mūša[at night]AV; ūm[day]N; n

2.	[{m}]{d}60--EN-šu₂-nu a-lid
#lem: ūmišu[day]N; Šamaš[1]DN

$ single ruling
# I've added various things for test purposes

#note: Note to line.

4.	<30> <(ina)> 12 GU U₄-ME-šu₂ GID₂-MEŠ{{ir-ri-ku}}
#lem: Sin[1]DN; ina[at]PRP; n; Gula[1]'CN; ūmūšu[day]N; +arāku[be(come) long]V$irrikū; +arāku[be(come) long]V$irrikū +.+. . 

5.	[GU₄].U₄ ina MAŠ₂ GENNA ina MIN<(MAŠ₂)>
#lem: Šihṭu[Mercury]CN; ina[in]PRP; Suhurmašu[Goatfish]CN +.+. . ; Kayyamanu[Saturn]CN; ina[in]PRP; Suhurmašu[Goatfish]CN

6.	[AN] ina ALLA <<ALLA>>
#lem: Ṣalbatanu[Mars]CN; ina[in]PRP; Alluttu[Crab]CN +.+. . 

7.    $BI x X |DU.DU| |GA₂×AN| |DU&DU| |LAGAB&LAGAB| DU@g GAN₂@t 4(BAN₂)@v
#lem: u; u; X; X; X; X; X; X; X; n

$ (a loose dollar line)

@reverse
$ reverse blank

@translation parallel en project
@obverse
1.	Year 63, Ṭebetu (Month X), night of day 2:^1^

@note ^1^ A note to the translation.

2.	Anu-belšunu was born.
3.	That day, the Sun was 9;30˚ in the Goat.
4.	The Moon was 12˚ in the Bucket: his days will be long.
5.	Jupiter was at the head of the Scorpion: someone will take the prince's hand.
6.	[The child] was born in the Bucket in the region of Venus: he will have sons.
7.	Mercury was in the Goat; Saturn was in the Goat;
```
and filename `filename`, without extension.  Run validation: the "Validation successful" pop up is always shown, even though there are errors.

**Expected behavior**

Get the "Validation identified errors. See log for details" pop up

**Additional context**

Like #90, the symptoms are similar to #89.

### PR DESCRIPTION
**Pull request by giordano**
Fix #99 by enforcing the `.atf` extension in the filename when submitting it to the server.  Happy to reword the error message if it isn't clear or it sounds odd.

Preview:

image

### CODE REVIEW

File: src/extension.ts [hunk 1]
```diff
@@ -71,6 +71,16 @@ async function workWithServer(verb: string, callback: ServerFunction): Promise<v
     const fileName = basename(editor.document.uri.fsPath);
     const fileContent = editor.document.getText();
     let fileProject: string;
+    // The server would not show errors when validating/lemmatising the file if
+    // it doesn't have the `.atf` extension.  We could work around this
+    // limitation, but not setting the extension correctly is likely an error
+    // anyway, so we enforce it to when submitting tasks to the server.
+    if (!fileName.match(/\.atf$/)) {
```
Comment (ageorgou) [inline src/extension.ts:78]: Is it a bit more readable to use [`endsWith`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith)?
```suggestion
    if (!fileName.endsWith(".atf")) {
```

**Review by ageorgou — APPROVED** [review]

**Comment by ageorgou** [comment]
I forgot to mention, the message looks fine to me! Maybe shorten the second sentence to "Please rename it." in case there is already a (different) extension so they would need to replace, not add it?
